### ISSUE TITLE
React 化（前端架构规划）

### ISSUE THREAD

**Issue by JimmyLv** [JimmyLv/blog-github-api-angular#69]
## 前端架构设计
- [ ] 抽取 Service，替换 Angular $http
- [ ] 设计 Model，并抽取 Mapper
- [ ] inline css
- [ ] 抽取 View 层成 UI Component / Layouts / Multiple Pages

http://guide.meteor.com/structure.html#example-app-structure

https://github.com/meteor/todos/tree/react
